### ISSUE TITLE
Rack::MethodOverride must be placed above all Controllers

### ISSUE THREAD

**Issue by lmilne360** [learn-co-curriculum/sinatra-restful-routes-readme#25]
It should be noted that not only does `use Rack::MethodOverride` need to be placed above application controller, but all other controller being `use`d for the middleware to actually work.

eg:

`use Rack::MethodOverride`
`use SomeController`
`use AnotherController`
`run ApplicationController`

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/sinatra-restful-routes-readme/commit/0e3a61a5476b1905259a9b412cd8a7b6975c0f4c. Thanks @lmilne360 !
