### ISSUE TITLE
Placement in Course Material

### ISSUE THREAD

**Issue by lilithlotus** [learn-co-curriculum/sinatra-restful-routes-readme#34]
I believe this lesson should be earlier in the AR section of Sinatra. Many of the patterns and explanations would have been very helpful in the previous labs and a great reference guide to use when going through the labs.

**Comment by DanielSeehausen** [comment]
Hi @lilithlotus!

Thank you for bringing this to our attention and providing feedback. This is valuable information for us when we think about the arc of entire curriculum sections, which will help us continue to improve the Sinatra section. 

Sincerely, 

The Learn Team  💙
