### ISSUE TITLE
KNOWN ISSUE: this reading should be before the Sinatra ActiveRecord CRUD lab

### ISSUE THREAD

**Issue by sparkbold** [learn-co-curriculum/sinatra-restful-routes-readme#40]

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#41.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
