### ISSUE TITLE
typo in Index Action example

### ISSUE THREAD

**Issue by Rexman17** [learn-co-curriculum/sinatra-restful-routes-readme#42]
![screen shot 2018-11-01 at 6 59 36 am](https://user-images.githubusercontent.com/37306273/47848175-e10e0400-dda3-11e8-8782-aa8d1c77b9e9.png)
the variable is set to singular @article but the description below it references the plural @articles

since it's an index, showing ALL articles, i believe it should be plural

**Comment by EvansJWang** [comment]
Thanks Ali! I fixed it!

**Comment by Rexman17** [comment]
Just saw this! Thank you
